[package]
name = "astr_data_compr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
flate2 = "1.0.26"
rust_decimal = "1.30.0"
rust_decimal_macros = "1.30.0"
walkdir = "2.3.3"
