[package]
name = "astr_data_compr"
version = "0.1.0"
edition = "2021"



[dependencies]
csv = "1.1"
flate2 = "1.0.26"
rust_decimal = "1.30.0"
rust_decimal_macros = "1.30.0"
walkdir = "2.3.3"
libc = "0.2.80"
cc = "1.0.28"
zfp-sys = "0.1.13"
